development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: behind-the-popcorn
  pool: 5
  username: root
  password: ha223UPS&!ee!
  socket: /srv/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: behind-the-popcorn
  pool: 5
  username: root
  password: ha223UPS&!ee!
  socket: /srv/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: behind-the-popcorn
  pool: 5
  username: root
  password: ha223UPS&!ee!
  socket: /srv/run/mysqld/mysqld.sock